### PR TITLE
Bundle aware package installation.

### PR DESCRIPTION
**Pull request by etugarev**
Hi

This is second merge attempt. Should be easier to read (as my experience with Github grows ;)

Comments to it is there https://github.com/wcm-io/wcm-io/pull/14

Regards,
Evgeny

### CODE REVIEW

**Comment by stefanseifert** [comment]
this sounds cool - will have a look into it soon.
which of the in #14 described strategies did you implement?

**Comment by etugarev** [comment]
Ah, indeed, I forgot to mention - it's the strategy 1

**Comment by stefanseifert** [comment]
thanks a lot for this patch! i applied if with some improvements/changes, namely:

- rename bundleInformationURL to bundleStatusURL and add javadocs and make it optional for backwards compatibility
- remove 3 retries to install package because this is already implemented via the "retryCount" parameter
- limit waiting for package status to 10min

i pushed a 1.0.1-SNAPSHOT version of this to the sonatype OSS maven repository.

**Comment by etugarev** [comment]
great, thanks! I will test new version and report here in case I found any issues.

**Pull request merged**
